# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=100)),
                ('colormode', models.BooleanField(default=False)),
                ('isdefaultPrinter', models.BooleanField(default=False)),
                ('duplex', models.BooleanField(default=False)),
                ('copies', models.IntegerField(default=1)),
                ('orientation', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
