# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160902_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='isdefaultPrinter',
            new_name='isdefaultprinter',
        ),
    ]
