# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_printer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('incolor', models.BooleanField(default=False)),
                ('copies', models.IntegerField(default=1)),
                ('orientation', models.CharField(max_length=20)),
                ('duplex', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='printer',
            old_name='colormode',
            new_name='colorcapable',
        ),
    ]
