# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160903_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='orientation',
        ),
    ]
